iwr https://angular.io/generated/zips/getting-started/getting-started.zip -O getting-started.zip
iwr https://angular.io/generated/zips/accessibility/accessibility.zip -O accessibility.zip
iwr https://angular.io/generated/zips/ajs-quick-reference/ajs-quick-reference.zip -O ajs-quick-reference.zip
iwr https://angular.io/generated/zips/animations/animations.zip -O animations.zip
iwr https://angular.io/generated/zips/architecture/architecture.zip -O architecture.zip
iwr https://angular.io/generated/zips/attribute-binding/attribute-binding.zip -O attribute-binding.zip
iwr https://angular.io/generated/zips/attribute-directives/attribute-directives.zip -O attribute-directives.zip
iwr https://angular.io/generated/zips/binding-syntax/binding-syntax.zip -O binding-syntax.zip
iwr https://angular.io/generated/zips/bootstrapping/bootstrapping.zip -O bootstrapping.zip
iwr https://angular.io/generated/zips/built-in-directives/built-in-directives.zip -O built-in-directives.zip
iwr https://angular.io/generated/zips/built-in-template-functions/built-in-template-functions.zip -O built-in-template-functions.zip
iwr https://angular.io/generated/zips/component-interaction/component-interaction.zip -O component-interaction.zip
iwr https://angular.io/generated/zips/component-styles/component-styles.zip -O component-styles.zip
iwr https://angular.io/generated/zips/dependency-injection-in-action/dependency-injection-in-action.zip -O dependency-injection-in-action.zip
iwr https://angular.io/generated/zips/dependency-injection/dependency-injection.zip -O dependency-injection.zip
iwr https://angular.io/generated/zips/docs-style-guide/docs-style-guide.zip -O docs-style-guide.zip
iwr https://angular.io/generated/zips/dynamic-component-loader/dynamic-component-loader.zip -O dynamic-component-loader.zip
iwr https://angular.io/generated/zips/dynamic-form/dynamic-form.zip -O dynamic-form.zip
iwr https://angular.io/generated/zips/elements/elements.zip -O elements.zip
iwr https://angular.io/generated/zips/event-binding/event-binding.zip -O event-binding.zip
iwr https://angular.io/generated/zips/feature-modules/feature-modules.zip -O feature-modules.zip
iwr https://angular.io/generated/zips/form-validation/form-validation.zip -O form-validation.zip
iwr https://angular.io/generated/zips/forms-overview/forms-overview.zip -O forms-overview.zip
iwr https://angular.io/generated/zips/forms/forms.zip -O forms.zip
iwr https://angular.io/generated/zips/getting-started/getting-started.zip -O getting-started.zip
iwr https://angular.io/generated/zips/hierarchical-dependency-injection/hierarchical-dependency-injection.zip -O hierarchical-dependency-injection.zip
iwr https://angular.io/generated/zips/http/http.zip -O http.zip
iwr https://angular.io/generated/zips/inputs-outputs/inputs-outputs.zip -O inputs-outputs.zip
iwr https://angular.io/generated/zips/interpolation/interpolation.zip -O interpolation.zip
iwr https://angular.io/generated/zips/lazy-loading-ngmodules/lazy-loading-ngmodules.zip -O lazy-loading-ngmodules.zip
iwr https://angular.io/generated/zips/lifecycle-hooks/lifecycle-hooks.zip -O lifecycle-hooks.zip
iwr https://angular.io/generated/zips/ngcontainer/ngcontainer.zip -O ngcontainer.zip
iwr https://angular.io/generated/zips/ngmodules/ngmodules.zip -O ngmodules.zip
iwr https://angular.io/generated/zips/pipes/pipes.zip -O pipes.zip
iwr https://angular.io/generated/zips/property-binding/property-binding.zip -O property-binding.zip
iwr https://angular.io/generated/zips/providers-viewproviders/providers-viewproviders.zip -O providers-viewproviders.zip
iwr https://angular.io/generated/zips/providers/providers.zip -O providers.zip
iwr https://angular.io/generated/zips/reactive-forms/reactive-forms.zip -O reactive-forms.zip
iwr https://angular.io/generated/zips/resolution-modifiers/resolution-modifiers.zip -O resolution-modifiers.zip
iwr https://angular.io/generated/zips/router-tutorial/router-tutorial.zip -O router-tutorial.zip
iwr https://angular.io/generated/zips/router/router.zip -O router.zip
iwr https://angular.io/generated/zips/security/security.zip -O security.zip
iwr https://angular.io/generated/zips/set-document-title/set-document-title.zip -O set-document-title.zip
iwr https://angular.io/generated/zips/structural-directives/structural-directives.zip -O structural-directives.zip
iwr https://angular.io/generated/zips/template-expression-operators/template-expression-operators.zip -O template-expression-operators.zip
iwr https://angular.io/generated/zips/template-reference-variables/template-reference-variables.zip -O template-reference-variables.zip
iwr https://angular.io/generated/zips/template-syntax/template-syntax.zip -O template-syntax.zip
iwr https://angular.io/generated/zips/toh-pt0/toh-pt0.zip -O toh-pt0.zip
iwr https://angular.io/generated/zips/toh-pt1/toh-pt1.zip -O toh-pt1.zip
iwr https://angular.io/generated/zips/toh-pt2/toh-pt2.zip -O toh-pt2.zip
iwr https://angular.io/generated/zips/toh-pt3/toh-pt3.zip -O toh-pt3.zip
iwr https://angular.io/generated/zips/toh-pt4/toh-pt4.zip -O toh-pt4.zip
iwr https://angular.io/generated/zips/toh-pt5/toh-pt5.zip -O toh-pt5.zip
iwr https://angular.io/generated/zips/toh-pt6/toh-pt6.zip -O toh-pt6.zip
iwr https://angular.io/generated/zips/toh-pt6/toh-pt6.zip -O toh-pt6.zip
iwr https://angular.io/generated/zips/two-way-binding/two-way-binding.zip -O two-way-binding.zip
iwr https://angular.io/generated/zips/user-input/user-input.zip -O user-input.zip
